### ISSUE TITLE
Cannot start container / httpd-server build breaks after step 31

### ISSUE THREAD

**Issue by myfear** [javaee-samples/docker-java#56] opened 2015-06-10 09:20 UTC
Not a happy birthday present, I know ;) 

Step 29 : ADD run-apache.sh /run-apache.sh
 ---> a92c5987d46d
Removing intermediate container c3d8a1076378
Step 30 : RUN chmod -v +x /run-apache.sh
 ---> Running in 77354a711cbe
mode of '/run-apache.sh' retained as 0755 (rwxr-xr-x)
 ---> 216bfc6ea101
Removing intermediate container 77354a711cbe
Step 31 : CMD /run-apache.sh
 ---> Running in 48dabeb5cb34
 ---> 97cf0220ca8b
Removing intermediate container 48dabeb5cb34
Successfully built 97cf0220ca8b
Cannot start container ca4c8e9094174e31d63e18a01793a0f9d3b4b93d0a6e1b7c76755bc555a59964: [8] System error: no such file or directory
{ instructor } master »

**Comment by arun-gupta** [comment] 2015-06-10 12:03
@myfear What script are you running? Which directory are you running from?

**Comment by myfear** [comment] 2015-06-10 12:09
docker-compose up - d from the instructor directory.

**Comment by arun-gupta** [comment] 2015-06-10 12:50
Just tried and concluded successfully as:

```
11c5fd509558: Pull complete
351f2cbcde5a: Pull complete
b25bde4f47f9: Pull complete
b39a445085a6: Already exists
registry:2.0: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:df3162e6cdecf84be7f5b79fbd73bfc19d3f96dc8f87ffd2838cc8cd5e9dd8bb
Status: Downloaded newer image for registry:2.0
Creating instructor_dockerregistry_1...
```

All changes are already committed into the workspace. Is your workspace current?

**Comment by rafabene** [comment] 2015-06-10 17:37
I also couldn't reproduce this issue. I'll close this issue. Please reopen if the issue persists

**Closed by rafabene** 2015-06-10 17:37 UTC
